version: '3.8'

services:
  crud_cards_webapi:
    image: ${DOCKER_REGISTRY-}crudcardswebapi
    build:
      context: .
      dockerfile: src/CRUD_Cards_webapi/Dockerfile
    environment:
       ConnectionStrings__PostgreeEF: ${POSTGREEEFCORE};
       ConnectionStrings__PostgreeDapper: ${POSGREEDAPPER};
       DapperDatabase: ${POSTGREEDAPPERCARDSDB};
    depends_on:
      - db

  identity_server:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: src/Identity_Server/Dockerfile
    environment:
       ConnectionStrings__Identity: ${POSTGREEIDENTITYEFCORE};
       JwtSettings__SecureCode: ${IDENTITYSECURECODE}
       JwtSettings__ValidAudience: crud_cards_webapi
       JwtSettings__ValidIssuer: identity_server
    depends_on:
      - identitydb
     

  identitydb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGREEUSER}
      POSTGRES_USER: ${POSTGREEPASSWORD}
    ports:
    - ${POSTGREEIDENTITYOUTPORT}:5432
    volumes:
    - ./tarxosgbsafetydata:/var/lib/postgresql/identitydata

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGREEUSER}
      POSTGRES_USER: ${POSTGREEPASSWORD}
    ports:
    - ${POSTGREEOUTPORT}:5432
    volumes:
    - ./tarxosgbsafetydata:/var/lib/postgresql/data

volumes:
  tarxosgbsafetydata: